### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by trebor** [Kcnarf/d3-voronoi-treemap#11]
i am in the process of building a nice chart on observable with this library, but my console gets swamped with log messages from the code.  it looks like there have been a few changes from the latest 1.1.0 release, including removal of these console log messages.  any chance you bump the version and push the release?

**Comment by Kcnarf** [comment]
If you only need a one-level partitioning (without nested partitions), please use the latest release of the d3-voronoi-map plugin.

If you need nested partitioning, logs come from the d3-voronoi-map dependency. Logs have been removed since v.2.0.1 (latest version). But the d3-voronoi-treemap plugin is stick to v.1.2.x release of the d3-voronoi-map plugin, where logs are still displayed. The solution is to produce a new v1.2.1 release, a log free version derived from v1.2.0.

Unfortunately, due to covid-19, it will be very difficult to do it at home. And I don't know when the end of confinement will take place.

**Comment by trebor** [comment]
thank you so much for the fast response, and the details!  ya i totally get how everything is delayed with the current lockdown.  my treemap project is what i'm doing to keep busy.  :)

i am using the nested partitions.  my goal is that have a nice reusable chart.  here is the flair dataset:

![image](https://user-images.githubusercontent.com/12802394/79076368-6b070f80-7cae-11ea-88cc-a3004ac5c19a.png)

by default, i'm slicing up the [turbo](https://github.com/d3/d3-scale-chromatic#interpolateTurbo) color space to help show tree structure. i'm working on zooming and other interactivity, all of which i will publish when it's in a clean state.  i can share out the private notebook with you beforehand if you are interested, though it's still a work in progress. :)

stay well!

**Comment by Kcnarf** [comment]
d3-voronoi-treemap v1.1.1 no longer floods console
