### ISSUE TITLE
voronoi-treemap without d3

### ISSUE THREAD

**Issue by SSCodeChamp** [Kcnarf/d3-voronoi-treemap#6]
I know this library is depends on some of the d3 libraries. But what are the chances of making it completely independent of d3 ? 

If you remove the dependency ,it will easy to transform this to any other programming language and use it on any other platform.

**Comment by Kcnarf** [comment]
Hi,
there is some legal/license issues. 

The authors of the scientific paper [Computing Voronoï Treemaps - Faster, Simpler, and Resolution-independent ](https://www.uni-konstanz.de/mmsp/pubsys/publishedFiles/NoBr12a.pdf) grant me rights "for the D3 community". It is clear that our exchanges only consider this usage/perimeter.

FYI, a JAVA implementation [https://github.com/ArlindNocaj/power-voronoi-diagram](https://github.com/ArlindNocaj/power-voronoi-diagram) provides a Java implementation, made by Arlind Nocaj, one of the author of the scientific paper. 

Note that if you don't want to load the entire D3 framework, as D3 is modular since its v4.0.0, you can only import the required packages:
```javascript
<script src="https://d3js.org/d3-hierarchy.v1.min.js"></script>
<script src="http://d3js.org/d3-polygon.v1.js" charset="utf-8"></script>
<script src="http://d3js.org/d3-array.v1.js" charset="utf-8"></script>
```

**Comment by SSCodeChamp** [comment]
Hi ,

How about creating this as a separate module in d3 ? and then that module takes care of adding the dependent d3 scripts ? In this way the users who wants to use voronoi have to add only one script and not to care of what it using internally.

Thanks

**Comment by Kcnarf** [comment]
Also, `d3_voronoi-treemap` deals with hierarchical data. This is currently handled with [d3-hierarchy](https://github.com/d3/d3-hierarchy) (various input formats, tree structure, summation/sort/... capabilities, and other things), and I don't want to re-invent the wheel
